// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportSystem.Infrastructure.Persistence;

#nullable disable

namespace SupportSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SupportSystemContext))]
    [Migration("20251113161141_InitialCreate")]
    // Configuração gerada que descreve o modelo alvo desta migração.
    partial class InitialCreate
    {
        // Reconstrói o modelo para que o EF Core possa comparar mudanças.
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupportSystem.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AbertoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<byte>("Prioridade")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedTechnicianId")
                        .HasColumnType("int");

                    b.Property<byte>("Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)255);

                    b.Property<DateTime?>("SlaTarget")
                        .HasColumnType("datetime2");

                    b.Property<string>("Solicitante")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SugestaoIa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Tickets", (string)null);

                    b.OwnsOne("SupportSystem.Domain.Entities.TicketFeedback", "Feedback", b1 =>
                        {
                            b1.Property<int?>("Nota")
                                .HasColumnName("FeedbackNota")
                                .HasColumnType("int");

                            b1.Property<string>("Comentario")
                                .HasColumnName("FeedbackComentario")
                                .HasColumnType("nvarchar(500)")
                                .HasMaxLength(500);

                            b1.Property<DateTime?>("RegistradoEm")
                                .HasColumnName("FeedbackRegistradoEm")
                                .HasColumnType("datetime2");

                            b1.WithOwner();
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AbertoEm = new DateTime(2024, 10, 10, 12, 30, 0, 0, DateTimeKind.Utc),
                            AssignedTechnicianId = 3,
                            Categoria = (byte)0,
                            Descricao = "Usuária relata falha ao autenticar na VPN corporativa após troca de senha.",
                            OwnerId = 1,
                            Prioridade = (byte)3,
                            SlaTarget = new DateTime(2024, 10, 11, 12, 30, 0, 0, DateTimeKind.Utc),
                            Solicitante = "Maria Silva",
                            Status = (byte)2,
                            SugestaoIa = "Verificar credenciais de AD, política de acesso e status do servidor TS.",
                            Titulo = "Erro ao acessar sistema via VPN"
                        },
                        new
                        {
                            Id = 2,
                            AbertoEm = new DateTime(2024, 10, 9, 11, 15, 0, 0, DateTimeKind.Utc),
                            Categoria = (byte)2,
                            Descricao = "Equipe de RH reporta demora ao calcular folha durante o fechamento do mês.",
                            OwnerId = 2,
                            Prioridade = (byte)2,
                            SlaTarget = new DateTime(2024, 10, 10, 17, 0, 0, 0, DateTimeKind.Utc),
                            Solicitante = "Depto RH",
                            Status = (byte)1,
                            SugestaoIa = "Conferir uso de CPU, memória do servidor e índices do banco.",
                            Titulo = "Lentidão no sistema de folha"
                        },
                        new
                        {
                            Id = 3,
                            AbertoEm = new DateTime(2024, 10, 8, 8, 45, 0, 0, DateTimeKind.Utc),
                            AssignedTechnicianId = 4,
                            Categoria = (byte)3,
                            Descricao = "Planejamento de atualização do ERP que envolve parada total do ambiente de produção.",
                            OwnerId = 3,
                            Prioridade = (byte)3,
                            SlaTarget = new DateTime(2024, 10, 8, 20, 45, 0, 0, DateTimeKind.Utc),
                            Solicitante = "Diretoria TI",
                            Status = (byte)4,
                            SugestaoIa = "Planejar janela de manutenção, snapshot do banco e rollback script.",
                            Titulo = "Atualização crítica do ERP"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
